databases:
  - name: aura-db
    plan: free
    databaseName: aura
    user: aura

services:
  - type: web
    name: AuraNITK
    plan: free
    runtime: node
    buildCommand: npm install && cd client && npm install --include=dev && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: ADMIN_MASTER_PASSWORD
        sync: false
